use_frameworks!

target 'EasyToast_Example' do
  pod 'EasyToast', :path => '../'

  target 'EasyToast_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.10.0'
    pod 'Nimble', '~> 5.0'
  end
end
